language: python
python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install libcups2-dev cups

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly
  - pip install coveralls flake8
  - pip install pycups==1.9.66
  - pip install PyPDF2==1.18
  - pip install requests
  - git clone https://github.com/OCA/reporting-engine -b ${VERSION} $HOME/reporting-engine

script:
  - travis_run_tests

after_success:
  coveralls
